#声明构建语言环境
language: android
dist: trusty
#开启基于容器的Travis CI任务，让编译效率更高。
sudo: false
#Git配置
git:
  #Travis CI可以clone存储库最大50次commit，这只有在执行git操作时才真正有用。
  #将git depth设置的值就是clone commit的次数，设置false取消clone commit次数限制。
  depth: false
#下载jdk8
jdk: oraclejdk8
#Android配置
android:
  #配置信息
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    # The BuildTools version used by your project
    #- build-tools-29.0.2
    # The SDK version used to compile your project
    #- android-29
    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
#缓存之前
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#缓存
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
#极早的流程步骤
before_install:
  #改变gradlew的访问权限
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;29.0.2"
  - yes | sdkmanager "build-tools;28.0.3"
  #安装fir命令行客户端
  - gem install fir-cli
  #生成配置文件
  - echo -e "CLIENT_ID=\"$CLIENT_ID\"" >> local.properties
  - echo -e "CLIENT_SECRET=\"$CLIENT_SECRET\"" >> local.properties
  - echo -e "GIT_NAME=\"$GIT_NAME\"" >> local.properties
  - echo -e "GIT_PWD=\"$GIT_PWD\"" >> local.properties
  - echo -e "FIR_ID=\"$FIR_ID\"" >> local.properties
  - echo -e "FIR_TOKEN=\"$FIR_TOKEN\"" >> local.properties
  - echo -e "STORE_RELEASE_FILE=$STORE_RELEASE_FILE" >> local.properties
  - echo -e "STORE_DEBUG_FILE=$STORE_DEBUG_FILE" >> local.properties
  - echo -e "STORE_PASSWORD=$STORE_PASSWORD" >> local.properties
  - echo -e "KEY_ALIAS=$KEY_ALIAS" >> local.properties
  - echo -e "KEY_PASSWORD=$KEY_PASSWORD" >> local.properties
  - ls
#脚本
script:
  - ./gradlew clean --scan
  - ./gradlew assembleRelease
#部署之前
before_deploy:
  #查看打包生成的Apk文件
  - ls release/outputs/apk/
#部署
deploy:
  #部署到GitHub Release
  provider: releases
  #填写GitHub的token
  api_key:
    secure: ${GH_TOKEN}
  #部署文件路径
  file: release/outputs/apk/module-app-$TRAVIS_TAG-release.apk
  #默认情况下Travis CI在完成编译后会清除所有生成的文件，设置为true以跳过清理
  skip_cleanup: true
  #部署时机
  on:
    tags: true
    all_branches: true
  #部署到GitHub仓库
  repo: coolfire2015/RxFluxArchApp
#部署之后
after_deploy:
  #fir账号的Token
  - fir login $FIR_TOKEN
  #打印身份信息,验证是否登录成功
  - fir me
  #自动发布应用至fir内测平台
  - fir publish release/outputs/apk/module-app-$TRAVIS_TAG-release.apk -c "`git cat-file tag $TRAVIS_TAG` | tail +6"
  #删除部署之后的apk
  - rm release/outputs/apk/module-app-$TRAVIS_TAG-release.apk
#通知
notifications:
  email:
    recipients:
      - 1049380320@qq.com
    on_success: change
    on_failure: always